Meta-Llama-3-70B-Instruct:
  prompt_template: "Meta-Llama-3-70B-Instruct/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "meta-llama/Llama-3-70b-chat-hf"
    max_tokens: 4096
    requires_chatml: True
    client_kwargs:
      base_url: 'https://api.together.xyz'
  batch_size: 1
  fn_completion_parser: null