Mixtral-8x22B-Instruct-v0.1:
  prompt_template: "Mixtral-8x22B-Instruct-v0.1/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "mistralai/Mixtral-8x22B-Instruct-v0.1"
    max_tokens: 4096
    requires_chatml: True
    client_kwargs:
      base_url: 'https://api.together.xyz'
  batch_size: 1
  fn_completion_parser: null
